# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sidekiq_username: <%= ENV["SIDEKIQ_USERNAME"] %>
  sidekiq_password: <%= ENV["SIDEKIQ_PASSWORD"] %>
  cm_sms_api_key: <%= ENV["CM_SMS_API_KEY"] %>
  cm_sms_send_from: 0502112595
  slack_booking_channel_webhook: <%= ENV["SLACK_BOOKING_CHANNEL_WEBHOOK"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  iban_from: NL76TRIO0338417702
  bic_from: TRIONL2U

test:
  <<: *default
  secret_key_base: 2e96d4294ff6e562d01fd4b5da6307d6d48735faaf78aea3774a9e05d607a488122eee9d9180b37ef342653a614eeb61fc1304a2aa87792e421a37f5121c4d7d

development:
  <<: *default
  secret_key_base: 6d1b8f517a0bffab0cd7e2b4f192c46160ad142ea0cc22f7597fd1e46af3b2167e9a4d12497a3a5478d5e828a910200fc5b5ff7689ab98a321939d35390fa18e

production:
  <<: *default

staging:
  <<: *default
  secret_key_base: 7d20574df1916e7eaef9dd6d631a86e952bba56f78ffec06356a9644afa1e2698b1df0fc3f7629dad46e1b7617228bf1842e5bd77f976be24f2f240e421402de